color: emerald
fieldLayouts:
  c7c042fa-70ce-4ebc-bbcd-e1c270d32573:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1c17380f-d22e-4f25-b38f-955a9dfe8153
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 897b7f07-b594-4d0e-91b4-d91914626ce5 # introductionform
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7b85b47-bb6f-4994-86f6-297a503de54b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d9e0f4e0-ca04-4976-8ab4-f07e6f63feab # form
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b952b6cc-88e9-49c9-89b1-98eb529a97d4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 79cc0474-269d-4603-9ce6-81704ac649db
        userCondition: null
handle: contentblock2
hasTitleField: true
icon: ''
name: contentblock2
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
