color: null
fieldLayouts:
  407040d4-136e-4f55-941d-10134efcfcd1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 576fa148-6dc1-4d55-91e0-5c1b650613f5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0fe840cb-dbe8-4928-9ab7-91a4d38bcbca # contacttitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31c84872-7737-4f39-a052-ae5cb1cd9987
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 346ff88a-4485-4cfe-9faf-31acc622d025 # contacttext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a5ef281-854d-435c-906c-f5ea0457ca04
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d9e0f4e0-ca04-4976-8ab4-f07e6f63feab # form
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d20c9ae-90db-4fbb-afd6-f315b5f09d7b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a39a4b35-5a01-4a38-b08b-c66e00c358f2
        userCondition: null
handle: contact
hasTitleField: true
icon: ''
name: contact
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
