color: null
fieldLayouts:
  4eed08cd-c378-4b3d-9c92-d7046d2b9401:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9bbe0216-2b40-436c-8a64-fb3c8dcb111f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0fe840cb-dbe8-4928-9ab7-91a4d38bcbca # contacttitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbe674d5-7d76-4a4b-ba8d-0dc50010233e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 346ff88a-4485-4cfe-9faf-31acc622d025 # contacttext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02536e34-180d-448a-8017-e8192568cd27
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a24a8485-6759-4c11-b6ef-5c7c5f4a013b # contentform
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ebff0d6-5312-4972-aa0c-9cc214b09003
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 33cd16f6-3e29-42a9-a5c7-118d1e4d7853
        userCondition: null
handle: formcontent
hasTitleField: false
icon: ''
name: formcontent
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: formcontent
titleTranslationKeyFormat: null
titleTranslationMethod: site
