color: null
fieldLayouts:
  2c28d62e-890d-4243-9a1b-4cbcae5e3db8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8ea7e516-2cb7-4e4b-9ae7-8e99be7ad591
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 897b7f07-b594-4d0e-91b4-d91914626ce5 # introductionform
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8d9689d-605f-4ac6-8e6a-5a0bfb620322
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6ea11ce3-1adb-4316-8974-c84980f3ed23
        userCondition: null
handle: formdescription
hasTitleField: false
icon: ''
name: formdescription
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'description block'
titleTranslationKeyFormat: null
titleTranslationMethod: site
