color: null
fieldLayouts:
  43ce26f0-cf2a-4ab6-8924-02d21132c23b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a9c89f2c-5679-4ab4-8248-39792bc9f9ec
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 99874d99-5a8f-4909-ba85-e14290046dd2
        userCondition: null
handle: gen1
hasTitleField: true
icon: ''
name: 'Gen 1'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
