color: null
fieldLayouts:
  8c895827-103c-4183-ba70-1b0f60564557:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f4c6907f-88da-4389-958b-3718fb2be2ee
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b726a0de-67fa-4cf0-af70-4a944f179ed2
        userCondition: null
handle: new
hasTitleField: true
icon: ''
name: New
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
