altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  72798e75-a002-4abd-b258-241c28150fee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 947fe0e5-1a65-4928-8d4b-f15f3940406d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 19460911-e612-4ca7-b5a1-dca50d43c070
        userCondition: null
fs: bannerimage
handle: bannerimage
name: bannerImage
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
