altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  5ec6004e-176b-451a-9a3e-4c01034ada78:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e2442257-831b-441a-a25e-a597b22b82e2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7d28b962-4fa4-4fd5-9bd1-51b42f68fc21
        userCondition: null
fs: products
handle: productwatches
name: productWatches
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
