columnSuffix: null
handle: blockbuilder1
instructions: null
name: blockbuilder1
searchable: true
settings:
  createButtonLabel: null
  entryTypes:
    - 6c9782d8-1816-42c5-b264-4b9f60b65409 # text
    - 9b9951bc-6fe2-42cd-ad5d-b9d699f8c0ed # image
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
