columnSuffix: null
handle: blockbuilder2
instructions: null
name: blockbuilder2
searchable: true
settings:
  createButtonLabel: null
  entryTypes:
    - 17734dec-c9ec-427a-8ce7-d1972d7cf873 # formtitle
    - a9701a37-5606-4a68-9933-2a8a0909d468 # formdescription
    - 61a6cdc0-8f75-480e-a863-dc75d9bf3847 # formblock
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
