dateModified: 1714488265
email:
  fromEmail: 12102082@student.pxl.be
  fromName: Timecraft
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    6fa87c78-1100-4f04-8cb2-f41fa486e80c: Timecraft # Timecraft
    d5ffdd0e-008d-450c-9cd2-3dff37e2134a: Timecraft # Timecraft
system:
  edition: pro
  live: true
  name: Timecraft
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
