defaultPlacement: end
enableVersioning: true
entryTypes:
  - fc00f804-b467-4408-9a42-fab4b41a9afa # introtext
handle: allProducts
maxAuthors: 1
name: 'All products'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d5ffdd0e-008d-450c-9cd2-3dff37e2134a: # Timecraft
    enabledByDefault: true
    hasUrls: true
    template: overzichtpagina.twig
    uriFormat: all-products
type: single
