defaultPlacement: end
enableVersioning: true
entryTypes:
  - 5a6f16c2-c4a6-4928-843b-39f6f133bdcc # welcomeHome
handle: timecraft
maxAuthors: 1
name: Timecraft
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d5ffdd0e-008d-450c-9cd2-3dff37e2134a: # Timecraft
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
